{% set version = '0.8.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsconnect
  version: {{ version|replace("-", "_") }}

source:
  fn: rsconnect_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsconnect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsconnect/rsconnect_{{ version }}.tar.gz
  sha256: 91825eca63172ed0d36f02a8db9c4e0a44188bb01af8341558398a5715873705

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat, rmarkdown (>= 1.1), plumber (>= 0.3.2), shiny, sourcetools, xtable
requirements:
  build:

  host:
    - r-base
    - r-pki
    - r-rcurl
    - r-rjsonio
    - r-digest
    - r-packrat >=0.4.8_1
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5

  run:
    - r-base
    - r-pki
    - r-rcurl
    - r-rjsonio
    - r-digest
    - r-packrat >=0.4.8_1
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rsconnect')"           # [not win]
    - "\"%R%\" -e \"library('rsconnect')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rsconnect
  license: GPL-2
  summary: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'RStudio Connect'.
    Supported content types include R Markdown documents, Shiny applications, Plumber
    APIs, plots, and static web content.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rsconnect
# Type: Package
# Title: Deployment Interface for R Markdown Documents and Shiny Applications
# Version: 0.8.8
# Author: JJ Allaire
# Maintainer: Jonathan McPherson <jonathan@rstudio.com>
# Description: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'RStudio Connect'. Supported content types include R Markdown documents, Shiny applications, Plumber APIs, plots, and static web content.
# Depends: R (>= 3.0.0)
# Imports: digest, PKI, RCurl, RJSONIO, packrat (>= 0.4.8-1), yaml (>= 2.1.5), rstudioapi (>= 0.5)
# Suggests: knitr, testthat, rmarkdown (>= 1.1), plumber (>= 0.3.2), shiny, sourcetools, xtable
# Enhances: BiocInstaller
# License: GPL-2
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-03-07 21:42:46 UTC; jmcphers
# Repository: CRAN
# Date/Publication: 2018-03-09 00:26:52 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
