travis:
  secure:
    BINSTAR_TOKEN: U9NwGD3XxJRoFemSk6t0mS3AgdlzhmppLoM6uB1FtshT8vmcG2IQkwLjo+5w4tRUFpXXLn8vMOnm7lP8olr2fUhlQmFZAiqGjnRrvOj0u3jsTYcQObrj2HuqjhW0VS4YPPexhgLFNEbQ9xOKZ1uq3uilufMwp4YZQEL0+90QLleBjplOYDmVE+1QxJZUqo4/iXeqdvJPoYUEhItIIb71SwHb0jmMgsByFSmGAdWK8VruRNs2kJhkL9MHV96y3WzzipuGwoocVQfHB+pQyIRQH8eP5K8Y6/m+nmswLY2lfNGB5SXZfqSC1GXGyfsHGV0Wn2ipH/rDWeQzCJXy/22l+rde84YpOb74IfC6t/NZt6WT/B0dGhC0bw1kvBrQ1N5ep4lmJTpPjmgwTRonxi0UyFM/j5qJAboXB/okjc63GgRAclMXruZUcagBaHqeiAefeiDOr84cMqnicAqn0HXvJKZRpIWHu8gs9Ulc4+hyI+AZDii8QGtUfsvSIaO5pYVlsqi7ll+MmGADTXBUelGPL4ktVXX1zVBec49IpS+FDJxwYeZLft1/3Lpt2nednmZKE4T0wEc4u4CKb4GR9n7tzfsZH12eE/mR50oPMIDR+LT/NmkScpRoQkcnuXxTcLyoRze0D1xfNnYyRs+9o2dlYf9w3JoxImvg+vydRWjJtmw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
