travis:
  secure:
    BINSTAR_TOKEN: drFuXIHaJ49VAWFJmkD2Jczxhl25m8d3BLJbMVuBK9ad0VSbqaay3KP8tIeBxaxnyvgVmGGC5wfZ7CpSz2itdZMlpkfDqnTYLKELQb3sm0zhHeQxoHRFuzQSG2ZfawT6WKgxCJpnSlgcPHJtw5Jhx6qdxO/3pKmyBJBbyN5ENkw+4Y0P8qkB3XXJurqnQwQjWecPIAD4zQqmUjH2VRP61xGGKdezsvssfTVgl54a4ST/skK2yhJ1T9JDeB/q9QeZeReWUgMw0LFuD29AT1XRgu9ns2RjSchF9ZsC52bFyQ/kraJV9eAI1PpxftpUCs3rrqb6tJoY0Jg0lXd2jiFDhdpZgEUATAS9q5LuclkbN0U5qtjQk5xFs1I964V1lJSF83cB/2eRpzc0EuHwDOp2wy7lr6A4Si1KRaixGxs+LIhzmpZ9WARQK8gSJ0QL70dISjAwWQ5isyMZsYVZ777TtP7o4V69keyg64J1sjT9w2UmLhi0sMXfxXiy40hYLHbtyijM5OodaZDO23rCduBz7EG1hTX+YAo8itDiDq3raKaZRx5SbMrbnhWld0n0bO7xZEH7xgp2jRdLuKeraAYv3GHLeHNXLRVibfY3ksNZlNKvHSvnVmhnyoBANkPpD4ZYsihndJUqFHeWkv2X/hgszsBRmZt0l8BE1QaBRPhsOW8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
